### ISSUE TITLE
Set Tensorflow GPU usage

### ISSUE THREAD

**Issue by MovEaxEax** [SciSharp/Keras.NET#202]
Is it possible yet to set the GPU usage of Tensorflow? The backend takes 23.6GB/24GB for training and predictions. The size of the dataset and models doesn't matter, it takes this amount of memory every time. In Python I can do something like this:

`# Assume that you have 12GB of GPU memory and want to allocate ~4GB:`
`gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)`
`sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))`

Code above taken from Stackoverflow. But works for me.

In Keras.NET I can't find anything like this. I appreciate any workaround aswell.

**_Offtopic:_**
Good work btw, I really like the C# implementation :) You did a great job

**Comment by MovEaxEax** [comment]
I found a solution for this. Keras.NET uses Python.Runtime.dll to connect with tensorflow. Add `using Python.Runtime;` to your code and the following lines, before use fit() or predict() methods:
`//Set Memory Growth`
`using (Py.GIL())`
`{`
`//Instance Tensorflow`
`dynamic tf = Py.Import("tensorflow");`
`//Enable memory groth`
`dynamic gpu = tf.config.experimental.list_physical_devices("GPU");`
`tf.config.experimental.set_memory_growth(device: gpu[0], enable: true);`
`}`
This executes the python commands for enabling memory growth, and tensorflow doesn't allocate the full available GPU memory. Works for tensorflow v2.4.1, for older versions you have to replace the python instructions  above with the older equivalent.

**EDIT:**
I want to share another solution, since the mixed .NET and Python calls end up in some trouble while using multiple threads. In my Windows Forms Application I need to run multiple threads. You can achieve this with stuff like `PythonEngine.BeginAllowThreads()` and `PythonEngine.EndAllowThreads()`, but the most handy solution for my code was to call directly the Python commands as string:

`PythonEngine.RunSimpleString("import tensorflow as tf;gpu = tf.config.list_physical_devices('GPU');tf.config.experimental.set_memory_growth(gpu[0], True);");`

Works like a charm. No troubles anymore.

Reference: https://github.com/pythonnet/pythonnet/pull/419

**Comment by fashrista** [comment]
In console app
![slika](https://user-images.githubusercontent.com/37577804/143619707-e26ba607-e2b2-435d-a139-105acfdfd1f4.png)


Both of the above solutions failed for me. The first one returned an empty array of GPUs. 
![slika](https://user-images.githubusercontent.com/37577804/143619482-dc2cd6f0-b6dd-4c9c-a00f-09f190a3f02b.png)

The second also fails:
![slika](https://user-images.githubusercontent.com/37577804/143619588-b8dd12af-6e04-484c-8c46-30322e7a2173.png)

Any suggestions?
Update: Had to install cuda and cudnn and update nvidia drivers. Now it works but is much slower than original keras in python.
